name: Check

on:
  push:
    branches: 
      - master
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.m2
          ~/.android/build-cache
        key: ${GITHUB_REF##*/}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Check with gradle
      run: ./gradlew check
    - name: Upload testDebugUnitTest results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: testDebugUnitTest
        path: ./**/build/reports/tests/testDebugUnitTest
